Intent : cricket score is added
the-vision/jarvis-core pull request #44
Opened 2020-03-15 10:16 UTC by gan3i

cricket score intent is added please take a look

2020-03-16 06:23 UTC, RohitRathore1 approved these changes

2020-04-20 14:33 UTC, gan3i commented
#27

2020-04-23 04:19 UTC, RohitRathore1 requested changes
@gan3i Please resolve the conflicts.

2020-04-24 15:40 UTC, gan3i commented
Closing this PR since I have deleted this branch and will not be able resolve conflicts, I will be creating a separate PR for this issue.

2020-04-24 15:40 UTC, closed without merging