Add new intents TIME and CONVERT TIME
the-vision/jarvis-core pull request #70
Opened 2020-04-17 14:26 UTC by csharp489

PR #68 
@TeAmP0is0N 
I have added new intents Time and Convert Time .Please check and review it.
Thanks

2020-04-18 13:13 UTC, RohitRathore1 approved these changes

2020-04-22 16:03 UTC, swapagarwal commented
Hi @csharp489!
Can you run the tests locally? You'll need to extract the times in the "convert_time" intent.

2020-04-23 04:05 UTC, TeAmP0is0N commented
@csharp489 Do the necessary changes.

2020-04-30 04:41 UTC, RohitRathore1 requested changes
@csharp489 Do the necessary changes.

2020-05-27 13:43 UTC, merged