Added new intent: video
the-vision/jarvis-core pull request #84
Opened 2020-05-17 02:51 UTC by adityabisoi

Closes #83

2020-05-17 04:14 UTC, TeAmP0is0N commented
@adityabisoi Build is failing https://travis-ci.org/github/the-vision/jarvis-core/builds/687948693

2020-05-17 17:05 UTC, adityabisoi commented
@TeAmP0is0N I have fixed the bug. Please review.

2020-05-23 05:46 UTC, RohitRathore1 approved these changes

2020-05-25 12:25 UTC, RohitRathore1 requested changes
@adityabisoi Resolve conflicts

2020-05-28 10:38 UTC, merged